dist: trusty
sudo: required
language: shell

services:
  - docker


before_install:
  - docker-compose --version
  - make build

script:
  - docker-compose -f docker-compose.test.yml run -e TRAVIS=$TRAVIS -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST oipa /app/src/bin/ci-run.sh
