# Docker Compose override file for running OIPA tests
# Extends 'docker-compose.yml'.
#

version: "2"
services:

  oipa:
    extends:
      file: docker-compose.yml
      service: oipa
    command: python manage.py test --nomigrations
    env_file:
      - etc/env/env.test
    # Required for Travis ci (coverage/coveralls)
    # volumes:
    #    - .:/app/src

  # DockerHub Autotest service
  sut:
    extends:
      service: oipa
    command:  python manage.py test --nomigrations
