# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    #branches:
      #only:
        #- feature/circleci

    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/OIPA

    steps:
      - checkout

      - run:
          name: install gdal dependencies
          command: |
            sudo apt-get update
            sudo apt-get install software-properties-common
            sudo add-apt-repository ppa:ubuntugis/ppa -y
            sudo apt-get update

            sudo apt-get install gdal-bin
            pip install gdal
            sudo apt-get install libgdal-dev

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "OIPA/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r OIPA/requirements.txt

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "OIPA/requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . env/bin/activate
            python OIPA/manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
